name: sui-build
run-name: Building Sui package bytecode
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-tools:mainnet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Sui package and dump bytecode as base64
        run: |
          sui move build
